function updateTime(elementId, offset) {
    const now = new Date();
    const utc = now.getTime() + (now.getTimezoneOffset() * 60000);
    const cityTime = new Date(utc + (3600000 * offset));
    const hours = cityTime.getHours().toString().padStart(2, '0');
    const minutes = cityTime.getMinutes().toString().padStart(2, '0');
    const seconds = cityTime.getSeconds().toString().padStart(2, '0');
    document.getElementById(elementId).textContent = `${hours}:${minutes}:${seconds}`;
}

document.addEventListener("DOMContentLoaded", function() {
    updateTime("moscow-time", 3); // Москва: GMT+3
    updateTime("spb-time", 3); // Санкт-Петербург: GMT+3
    updateTime("ekb-time", 5); // Екатеринбург: GMT+5
    updateTime("novosibirsk-time", 7); // Новосибирск: GMT+7
    updateTime("krasnoyarsk-time", 7); // Красноярск: GMT+7
    updateTime("ny-time", -4); // Нью-Йорк: GMT-4
    updateTime("la-time", -7); // Лос-Анджелес: GMT-7
    updateTime("chicago-time", -5); // Чикаго: GMT-5
    updateTime("houston-time", -5); // Хьюстон: GMT-5
    updateTime("philadelphia-time", -4); // Филадельфия: GMT-4
    updateTime("london-time", 0); // Лондон: GMT
    updateTime("birmingham-time", 0); // Бирмингем: GMT
    updateTime("liverpool-time", 0); // Ливерпуль: GMT
    updateTime("manchester-time", 0); // Манчестер: GMT
    updateTime("glasgow-time", 0); // Глазго: GMT
    updateTime("toronto-time", -4); // Торонто: GMT-4
    updateTime("vancouver-time", -7); // Ванкувер: GMT-7
    updateTime("montreal-time", -4); // Монреаль: GMT-4
    updateTime("calgary-time", -6); // Калгари: GMT-6
    updateTime("ottawa-time", -4); // Оттава: GMT-4
    updateTime("beijing-time", 8); // Пекин: GMT+8
    updateTime("shanghai-time", 8); // Шанхай: GMT+8
    updateTime("guangzhou-time", 8); // Гуанчжоу: GMT+8
    updateTime("shenzhen-time", 8); // Шэньчжэнь: GMT+8
    updateTime("chongqing-time", 8); // Чунцин: GMT+8
    updateTime("tokyo-time", 9); // Токио: GMT+9
    updateTime("osaka-time", 9); // Осака: GMT+9
    updateTime("nagoya-time", 9); // Нагоя: GMT+9
    updateTime("sapporo-time", 9); // Саппоро: GMT+9
    updateTime("kyoto-time", 9); // Киото: GMT+9
    updateTime("paris-time", 1); // Париж: GMT+1
    updateTime("marseille-time", 1); // Марсель: GMT+1
    updateTime("lyon-time", 1); // Лион: GMT+1
    updateTime("toulouse-time", 1); // Тулуза: GMT+1
    updateTime("nice-time", 1); // Ницца: GMT+1
    updateTime("delhi-time", 5.5); // Нью-Дели: GMT+5.5
    updateTime("mumbai-time", 5.5); // Мумбаи: GMT+5.5
    updateTime("bangalore-time", 5.5); // Бангалор: GMT+5.5
    updateTime("chennai-time", 5.5); // Ченнаи: GMT+5.5
    updateTime("kolkata-time", 5.5); // Калькутта: GMT+5.5
    updateTime("berlin-time", 2); // Берлин: GMT+2
    updateTime("hamburg-time", 2); // Гамбург: GMT+2
    updateTime("munich-time", 2); // Мюнхен: GMT+2
    updateTime("cologne-time", 2); // Кёльн: GMT+2
    updateTime("frankfurt-time", 2); // Франкфурт-на-Майне: GMT+2
    updateTime("rome-time", 2); // Рим: GMT+2
    updateTime("milan-time", 2); // Милан: GMT+2
    updateTime("naples-time", 2); // Неаполь: GMT+2
    updateTime("turin-time", 2); // Турин: GMT+2
    updateTime("palermo-time", 2); // Палермо: GMT+2
    updateTime("saopaulo-time", -3); // Сан-Паулу: GMT-3
    updateTime("riodejaneiro-time", -3); // Рио-де-Жанейро: GMT-3
    updateTime("brasilia-time", -3); // Бразилиа: GMT-3
    updateTime("salvador-time", -3); // Сальвадор: GMT-3
    updateTime("fortaleza-time", -3); // Форталеза: GMT-3
    updateTime("sydney-time", 10); // Сидней: GMT+10
    updateTime("melbourne-time", 10); // Мельбурн: GMT+10
    updateTime("brisbane-time", 10); // Брисбен: GMT+10
    updateTime("perth-time", 8); // Перт: GMT+8
    updateTime("adelaide-time", 9.5); // Аделаида: GMT+9.5
    updateTime("madrid-time", 2); // Мадрид: GMT+2
    updateTime("barcelona-time", 2); // Барселона: GMT+2
    updateTime("valencia-time", 2); // Валенсия: GMT+2
    updateTime("seville-time", 2); // Севилья: GMT+2
    updateTime("zaragoza-time", 2); // Сарагоса: GMT+2
    updateTime("mexicocity-time", -5); // Мехико: GMT-5
    updateTime("guadalajara-time", -5); // Гвадалахара: GMT-5
    updateTime("monterrey-time", -5); // Монтеррей: GMT-5
    updateTime("puebla-time", -5); // Пуэбла: GMT-5
    updateTime("toluca-time", -5); // Толука: GMT-5
    updateTime("seoul-time", 9); // Сеул: GMT+9
    updateTime("busan-time", 9); // Пусан: GMT+9
    updateTime("incheon-time", 9); // Инчхон: GMT+9
    updateTime("daegu-time", 9); // Даегу: GMT+9
    updateTime("daejeon-time", 9); // Даеун: GMT+9
    updateTime("riyadh-time", 3); // Эр-Рияд: GMT+3
    updateTime("jeddah-time", 3); // Джидда: GMT+3
    updateTime("mecca-time", 3); // Мекка: GMT+3
    updateTime("medina-time", 3); // Медина: GMT+3
    updateTime("dammam-time", 3); // Даммам: GMT+3
    updateTime("zurich-time", 2); // Цюрих: GMT+2
    updateTime("geneva-time", 2); // Женева: GMT+2
    updateTime("basel-time", 2); // Базель: GMT+2
    updateTime("lausanne-time", 2); // Лозанна: GMT+2
    updateTime("bern-time", 2); // Берн: GMT+2
    updateTime("stockholm-time", 2); // Стокгольм: GMT+2
    updateTime("gothenburg-time", 2); // Гётеборг: GMT+2
    updateTime("malmo-time", 2); // Мальмё: GMT+2
    updateTime("uppsala-time", 2); // Уппсала: GMT+2
    updateTime("vasteras-time", 2); // Вестерос: GMT+2
    updateTime("amsterdam-time", 2); // Амстердам: GMT+2
    updateTime("rotterdam-time", 2); // Роттердам: GMT+2
    updateTime("thehague-time", 2); // Гаага: GMT+2
    updateTime("utrecht-time", 2); // Утрехт: GMT+2
    updateTime("eindhoven-time", 2); // Эйндховен: GMT+2
    updateTime("oslo-time", 2); // Осло: GMT+2
    updateTime("bergen-time", 2); // Берген: GMT+2
    updateTime("stavanger-time", 2); // Ставангер: GMT+2
    updateTime("trondheim-time", 2); // Тронхейм: GMT+2
    updateTime("tromso-time", 2); // Тромсё: GMT+2
});
